packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'
catalogs:
  dev:
    '@antfu/eslint-config': ^4.16.1
    '@eslint-react/eslint-plugin': ^1.52.2
    '@eslint/js': ^9.8.0
    '@swc/jest': ~0.2.36
    '@types/jest': ^29.5.12
    esbuild: ^0.25.5
    eslint: ^9.8.0
    eslint-flat-config-utils: ^2.1.0
    eslint-plugin-better-tailwindcss: ^3.4.3
    eslint-plugin-format: ^1.0.1
    eslint-plugin-jsx-a11y: ^6.10.2
    eslint-plugin-promise: ^7.2.1
    eslint-plugin-unicorn: ^59.0.1
    jest: ^29.7.0
    jest-environment-node: ^29.7.0
    tailwindcss: ^4.1.11
    ts-jest: ^29.1.0
    ts-node: 10.9.2
    typescript-eslint: ^8.35.1
onlyBuiltDependencies:
  - '@swc/core'
  - nx
