packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  '@antfu/eslint-config': ^4.16.2
  '@effect/vitest': ^0.23.12
  '@eslint-react/eslint-plugin': ^1.52.2
  '@eslint/js': ^9.30.1
  '@radix-ui/react-dialog': ^1.1.14
  '@radix-ui/react-slot': ^1.2.3
  '@storybook/addon-a11y': 9.0.15
  '@storybook/addon-docs': 9.0.15
  '@storybook/addon-themes': 9.0.15
  '@storybook/addon-vitest': 9.0.15
  '@storybook/react': 9.0.15
  '@storybook/react-vite': 9.0.15
  '@tailwindcss/cli': 4.1.11
  '@tailwindcss/vite': 4.1.11
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  effect: 3.16.12
  eslint-flat-config-utils: ^2.1.0
  eslint-plugin-better-tailwindcss: ^3.4.3
  eslint-plugin-format: ^1.0.1
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-promise: ^7.2.1
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-plugin-unicorn: ^59.0.1
  globals: ^16.3.0
  i18next: 25.3.1
  lucide-react: ^0.525.0
  obsidian: latest
  react: ^18.3.1
  react-dom: ^18.3.1
  remeda: 2.24.0
  shadcn: ^2.7.0
  tailwind-merge: ^3.3.1
  tailwindcss: 4.1.11
  ts-essentials: ^10.1.1
  tw-animate-css: ^1.3.5

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - nx
