packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  '@radix-ui/react-dialog': ^1.1.14
  '@radix-ui/react-slot': ^1.2.3
  '@storybook/addon-a11y': ^9.0.15
  '@storybook/addon-docs': ^9.0.15
  '@storybook/addon-themes': ^9.0.15
  '@tailwindcss/vite': ^4.1.11
  cmdk: ^1.1.1
  lucide-react: ^0.525.0
  react: 19.0.0
  react-dom: 19.0.0

catalogs:
  dev:
    '@antfu/eslint-config': ^4.16.1
    '@eslint-react/eslint-plugin': ^1.52.2
    '@eslint/js': ^9.8.0
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    esbuild: ^0.25.0
    eslint: ^9.8.0
    eslint-flat-config-utils: ^2.1.0
    eslint-plugin-better-tailwindcss: ^3.4.3
    eslint-plugin-format: ^1.0.1
    eslint-plugin-jsx-a11y: ^6.10.2
    eslint-plugin-promise: ^7.2.1
    eslint-plugin-react: 7.35.0
    eslint-plugin-react-hooks: 5.0.0
    eslint-plugin-react-refresh: ^0.4.20
    eslint-plugin-unicorn: ^59.0.1
    shadcn: ^2.7.0
    tailwind-merge: ^3.3.1
    tailwindcss: ^4.1.11
    tw-animate-css: 1.3.5
    typescript-eslint: ^8.35.1

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - nx
