packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  '@antfu/eslint-config': ^4.16.2
  '@effect/vitest': ^0.23.13
  '@eslint-react/eslint-plugin': ^1.52.3
  '@eslint/js': ^9.31.0
  '@preact': ^0.0.0
  '@preact/comapt': ^0.0.0
  '@preact/compat': 18.3.1
  '@preact/preset-vite': ^2.10.2
  '@radix-ui/react-dialog': 1.1.14
  '@radix-ui/react-slot': 1.2.3
  '@storybook/addon-a11y': 9.0.16
  '@storybook/addon-docs': 9.0.16
  '@storybook/addon-themes': 9.0.16
  '@storybook/addon-vitest': 9.0.16
  '@storybook/preact-vite': ^9.0.16
  '@tailwindcss/vite': 4.1.11
  '@testing-library/dom': 10.4.0
  '@testing-library/preact': ^3.2.4
  '@types/react': 19.1.8
  '@types/react-dom': 19.1.6
  '@vitejs/plugin-react': ^0.0.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: 1.1.1
  effect: 3.16.13
  eslint-flat-config-utils: ^2.1.0
  eslint-plugin-better-tailwindcss: ^3.5.2
  eslint-plugin-format: ^1.0.1
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-promise: ^7.2.1
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-plugin-unicorn: ^59.0.1
  globals: ^16.3.0
  i18next: 25.3.2
  lucide-react: ^0.525.0
  obsidian: ^1.8.7
  preact: ^10.26.9
  react: npm:@preact/compat@latest
  react-docgen-typescript: ^2.4.0
  react-dom: npm:@preact/compat@latest
  remeda: 2.25.0
  shadcn: ^2.9.0
  storybook: 9.0.16
  tailwind-merge: ^3.3.1
  tailwindcss: 4.1.11
  ts-essentials: ^10.1.1
  tw-animate-css: 1.3.5

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - nx
