const { builtinModules } = require('node:module')

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const production = process.env.NODE_ENV === 'production'

module.exports = {
  banner: {
    js: banner,
  },
  bundle: true,
  entryPoints: ['apps/little-bot/src/main.ts'],
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules,
  ],
  format: 'cjs',
  logLevel: 'info',
  minify: production,
  outExtension: {
    '.js': '.js',
  },
  platform: 'node',
  // sourcemap: prod ? false : "inline",
  sourcemap: false,
  target: 'es2018',
  treeShaking: true,
}
